branch-defaults:
  master:
    environment: RetropolisApiBackend-env
deploy:
  artifact: target/com.codurance.retropolis.backend-0.0.1-SNAPSHOT.jar
global:
  application_name: retropolis-api-backend
  default_ec2_keyname: null
  default_platform: Corretto 11 running on 64bit Amazon Linux 2/3.0.1
  default_region: us-east-1
  sc: git