branch-defaults:
  master:
    environment: RetropolisApi-env
deploy:
  artifact: target/com.codurance.retropolis.backend-0.0.1-SNAPSHOT.jar
global:
  application_name: retropolis-api
  default_ec2_keyname: null
  default_platform: Corretto 11 running on 64bit Amazon Linux 2/3.0.1
  default_region: eu-west-2
  sc: git